# Generated by Django 5.2.15 on 2026-06-19 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_fix_blank_article_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to generate an SEO-friendly Hinglish URL from the Hindi title.', max_length=240, unique=True),
        ),
        migrations.CreateModel(
            name='ArticleSlugRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(max_length=240, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_redirects', to='news.article')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
