# Generated by Django 5.2.15 on 2026-06-24 19:17

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_article_unique_reads_articleread'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('rss_url', models.URLField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_sources', to='news.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FetchedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_title', models.CharField(max_length=300)),
                ('original_url', models.URLField(unique=True)),
                ('original_summary', models.TextField(blank=True)),
                ('ai_title', models.CharField(blank=True, max_length=220)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='AI Content')),
                ('ai_slug', models.SlugField(blank=True, max_length=240)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('draft', 'Draft'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to='news.article')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetched_news', to='news.newssource')),
            ],
            options={
                'verbose_name': 'Fetched news',
                'verbose_name_plural': 'Fetched news',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='newssource',
            index=models.Index(fields=['is_active', 'name'], name='news_source_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='fetchednews',
            index=models.Index(fields=['status', '-fetched_at'], name='news_fetch_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='fetchednews',
            index=models.Index(fields=['source', '-fetched_at'], name='news_fetch_source_time_idx'),
        ),
    ]
