# Generated by Django 5.2.15 on 2026-06-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_newssource_fetchednews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchednews',
            name='fact_points',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fetchednews',
            name='internal_note',
            field=models.TextField(default='Draft generated from source facts; editor review required.'),
        ),
        migrations.AddField(
            model_name='fetchednews',
            name='source_credit',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='fetchednews',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
