# Generated by Django 5.2.15 on 2026-07-27 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_article_facebook_post_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='correction_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='fact_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact_checked_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='image_caption',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='article',
            name='image_credit',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='article',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
