# Generated by Codex for The UP Media mobile backend downloads

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("live_tv", "0009_mobilevideoupload_uploaded_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaDownload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=180)),
                ("source_url", models.URLField(max_length=1200)),
                ("media_type", models.CharField(choices=[("video", "Video"), ("audio", "Audio"), ("unknown", "Unknown")], default="unknown", max_length=20)),
                ("downloaded_file", models.FileField(blank=True, null=True, upload_to="media-downloads/%Y/%m/")),
                ("status", models.CharField(choices=[("processing", "Processing"), ("done", "Done"), ("failed", "Failed")], default="processing", max_length=20)),
                ("progress_percent", models.PositiveSmallIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="live_tv_media_downloads", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
