# Generated by Codex for separated Live TV settings

from django.db import migrations, models


def create_default_settings(apps, schema_editor):
    LiveTVSetting = apps.get_model("live_tv", "LiveTVSetting")
    LiveTVSetting.objects.get_or_create(pk=1, defaults={"name": "The Up Media Live TV"})


class Migration(migrations.Migration):

    dependencies = [
        ("live_tv", "0010_mediadownload"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveTVSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="The Up Media Live TV", max_length=120)),
                ("live_label", models.CharField(default="LIVE", max_length=40)),
                ("channel_logo", models.ImageField(blank=True, null=True, upload_to="live-tv/settings/")),
                ("show_live_badge", models.BooleanField(default=True)),
                ("show_channel_logo", models.BooleanField(default=True)),
                ("show_lower_third", models.BooleanField(default=True)),
                ("show_ticker", models.BooleanField(default=True)),
                ("autoplay", models.BooleanField(default=False)),
                ("default_lower_third_label", models.CharField(default="BREAKING NEWS", max_length=60)),
                ("default_headline", models.CharField(default="The Up Media Live TV", max_length=180)),
                ("default_ticker_label", models.CharField(default="TODAY'S NEWS", max_length=60)),
                ("default_ticker_text", models.CharField(default="Latest updates from The Up Media", max_length=260)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "Live TV Setting", "verbose_name_plural": "Live TV Settings"},
        ),
        migrations.RunPython(create_default_settings, migrations.RunPython.noop),
    ]
