# Generated by Codex for separating channel content from global Live TV settings

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_tv", "0011_livetvsetting"),
    ]

    operations = [
        migrations.RemoveField(model_name="livetvchannel", name="autoplay"),
        migrations.RemoveField(model_name="livetvchannel", name="channel_logo"),
        migrations.RemoveField(model_name="livetvchannel", name="show_channel_logo"),
        migrations.RemoveField(model_name="livetvchannel", name="show_lower_third"),
        migrations.RemoveField(model_name="livetvchannel", name="show_ticker"),
        migrations.AlterField(
            model_name="livetvchannel",
            name="ticker_text",
            field=models.TextField(default="Latest updates from The Up Media"),
        ),
    ]
