# Generated by Codex for Live TV ticker speed setting

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_tv", "0012_simplify_livetvchannel"),
    ]

    operations = [
        migrations.AddField(
            model_name="livetvsetting",
            name="ticker_speed_seconds",
            field=models.PositiveSmallIntegerField(default=22),
        ),
    ]
