# Generated by Codex for separate mobile ticker speed setting

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_tv", "0013_livetvsetting_ticker_speed_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="livetvsetting",
            name="mobile_ticker_speed_seconds",
            field=models.PositiveSmallIntegerField(default=12),
        ),
    ]