# Generated by Codex for Facebook Live RTMPS settings

from django.db import migrations, models


def create_default_facebook_live_setting(apps, schema_editor):
    FacebookLiveSetting = apps.get_model("live_tv", "FacebookLiveSetting")
    FacebookLiveSetting.objects.get_or_create(pk=1, defaults={"name": "Facebook Live"})


class Migration(migrations.Migration):

    dependencies = [
        ("live_tv", "0014_livetvsetting_mobile_ticker_speed_seconds"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookLiveSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Facebook Live", max_length=120)),
                ("server_url", models.URLField(default="rtmps://live-api-s.facebook.com:443/rtmp/", max_length=500)),
                ("stream_key", models.CharField(blank=True, max_length=500)),
                ("is_enabled", models.BooleanField(default=False)),
                ("status", models.CharField(choices=[("stopped", "Stopped"), ("starting", "Starting"), ("live", "Live"), ("failed", "Failed")], default="stopped", max_length=20)),
                ("process_id", models.PositiveIntegerField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Facebook Live Setting",
                "verbose_name_plural": "Facebook Live Settings",
            },
        ),
        migrations.RunPython(create_default_facebook_live_setting, migrations.RunPython.noop),
    ]