# Generated by Codex to allow RTMPS Facebook server URLs

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_tv", "0015_facebooklivesetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facebooklivesetting",
            name="server_url",
            field=models.CharField(default="rtmps://live-api-s.facebook.com:443/rtmp/", max_length=500),
        ),
    ]