# Generated by Codex for Facebook Live FFmpeg log tracking

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_tv", "0016_alter_facebooklivesetting_server_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebooklivesetting",
            name="log_file",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]