# Generated by Django 5.2.15 on 2026-07-12 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0020_blank_channel_lower_third'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortsVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180)),
                ('caption', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('audio_title', models.CharField(default='मूल ऑडियो - The UP Media', max_length=120)),
                ('video_file', models.FileField(upload_to='shorts/videos/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='shorts/thumbnails/%Y/%m/')),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_tv_shorts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['is_published', 'display_order'], name='shorts_published_order_idx')],
            },
        ),
    ]
