# Generated by Django 5.2.15 on 2026-07-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0021_shortsvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortsvideo',
            name='audio_title',
            field=models.CharField(default='Original Audio - The UP Media', max_length=120),
        ),
    ]
