# Generated by Django 5.2.15 on 2026-07-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0022_alter_shortsvideo_audio_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortsvideo',
            name='frame_template',
            field=models.CharField(default='normal_black_red', max_length=60),
        ),
        migrations.AddField(
            model_name='shortsvideo',
            name='headline',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
