# Generated by Django 5.2.15 on 2026-07-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0023_shortsvideo_frame_template_shortsvideo_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortsvideo',
            name='audio_title',
        ),
    ]
