# Generated by Django 5.2.15 on 2026-07-13 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0025_livetvcategory_livetvstate_livetvchannel_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTVCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='live_tv.livetvstate')),
            ],
            options={
                'verbose_name': 'Live TV City',
                'verbose_name_plural': 'Live TV Cities',
                'ordering': ['state__display_order', 'state__name', 'display_order', 'name'],
                'unique_together': {('state', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='livetvchannel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='live_tv.livetvcity'),
        ),
        migrations.AlterField(
            model_name='shortsvideo',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shorts', to='live_tv.livetvcity'),
        ),
    ]
