# Generated by Django 5.2.15 on 2026-07-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0027_shortscomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortsvideo',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shortsvideo',
            name='hls_master_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='shortsvideo',
            name='hls_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='shortsvideo',
            name='original_video',
            field=models.FileField(blank=True, null=True, upload_to='shorts/original/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='shortsvideo',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
    ]
