# Generated by Django 5.2.15 on 2026-07-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0028_shortsvideo_duration_shortsvideo_hls_master_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetvchannel',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livetvchannel',
            name='hls_master_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='livetvchannel',
            name='hls_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='livetvchannel',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
    ]
