# Generated by Django 5.2.15 on 2026-07-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0029_livetvchannel_duration_livetvchannel_hls_master_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppHomeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='THE UP MEDIA', max_length=120)),
                ('subtitle', models.CharField(default='Live TV and videos', max_length=180)),
                ('hero_badge', models.CharField(default='LIVE TV', max_length=40)),
                ('hero_button_text', models.CharField(default='Live dekhein', max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='live-tv/home-settings/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Home Setting',
                'verbose_name_plural': 'App Home Settings',
            },
        ),
        migrations.CreateModel(
            name='AppMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('target_type', models.CharField(default='section', help_text='section, live_tv, shorts, videos, district, url', max_length=40)),
                ('target_value', models.CharField(blank=True, max_length=180)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'App Menu',
                'verbose_name_plural': 'App Menus',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('featured', 'Mukhya Khabrein'), ('top_video', 'Top Video')], default='featured', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=220)),
                ('badge_text', models.CharField(blank=True, max_length=40)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='live-tv/home/%Y/%m/')),
                ('image_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('stream_type', models.CharField(choices=[('direct', 'Direct MP4'), ('hls', 'HLS / M3U8'), ('youtube', 'YouTube'), ('action', 'App Action')], default='direct', max_length=20)),
                ('duration', models.CharField(blank=True, max_length=24)),
                ('viewers_count', models.PositiveIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Content',
                'verbose_name_plural': 'Home Contents',
                'ordering': ['section', 'display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeUtility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('subtitle', models.CharField(blank=True, max_length=160)),
                ('icon', models.CharField(default='play-circle', max_length=40)),
                ('action', models.CharField(default='live_tv', max_length=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Utility',
                'verbose_name_plural': 'Home Utilities',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
