# Generated by Django 5.2.15 on 2026-07-14 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0030_apphomesetting_appmenu_homecontent_homeutility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shortsvideo',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ChannelFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_tv_followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_tv_following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['channel_user', 'user'], name='channel_follow_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'channel_user'), name='unique_live_tv_channel_follow')],
            },
        ),
        migrations.CreateModel(
            name='ShortsLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_likes', to='live_tv.shortsvideo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_live_tv_shorts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['short', 'user'], name='shorts_like_short_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('short', 'user'), name='unique_shorts_like_user')],
            },
        ),
    ]
