# Generated by Django 5.2.15 on 2026-07-14 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0033_repair_livetvchannel_location_nulls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socialrenderedvideo',
            name='broadcast_session_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='socialrenderedvideo',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialrenderedvideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialrenderedvideo',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialrenderedvideo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socialrenderedvideo',
            name='is_downloadable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socialrenderedvideo',
            name='live_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_broadcast_renders', to='live_tv.livetvchannel'),
        ),
        migrations.AddField(
            model_name='socialrenderedvideo',
            name='playlist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendered_broadcasts', to='live_tv.livetvplaylistitem'),
        ),
        migrations.AddField(
            model_name='socialrenderedvideo',
            name='render_key',
            field=models.CharField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='socialrenderedvideo',
            name='resolution',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='socialrenderedvideo',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialrenderedvideo',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socialrenderedvideo',
            name='source_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_rendered_videos', to='live_tv.livetvchannel'),
        ),
        migrations.AddField(
            model_name='socialrenderedvideo',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialrenderedvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='social-render/thumbnails/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='socialrenderedvideo',
            name='original_video',
            field=models.FileField(blank=True, null=True, upload_to='social-render/original/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='socialrenderedvideo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('done', 'Done'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
        migrations.AddIndex(
            model_name='socialrenderedvideo',
            index=models.Index(fields=['status', '-created_at'], name='rendered_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='socialrenderedvideo',
            index=models.Index(fields=['live_channel', 'broadcast_session_id'], name='rendered_session_idx'),
        ),
    ]
