# Generated by Django 5.2.15 on 2026-07-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0035_delete_apphomesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetvsetting',
            name='default_headline',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='livetvsetting',
            name='default_lower_third_label',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='livetvsetting',
            name='default_ticker_label',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='livetvsetting',
            name='default_ticker_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
