# Generated by Django 5.2.15 on 2026-07-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0036_alter_livetvsetting_default_headline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialrenderedvideo',
            name='ticker_text',
            field=models.TextField(blank=True),
        ),
    ]
