# Generated by Codex on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_tv", "0037_alter_socialrenderedvideo_ticker_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="livetvchannel",
            name="hls_progress_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shortsvideo",
            name="hls_progress_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
