# Generated by Django 5.2.15 on 2026-07-20 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0039_push_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetvsetting',
            name='ticker_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
