# Generated by Django 5.2.15 on 2026-07-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0045_livetvsetting_maximum_headline_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortsvideo',
            name='channel_logo',
            field=models.ImageField(blank=True, null=True, upload_to='shorts/logos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='shortsvideo',
            name='channel_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='shortsvideo',
            name='frame_background_color',
            field=models.CharField(default='#050505', max_length=20),
        ),
        migrations.AddField(
            model_name='shortsvideo',
            name='frame_primary_color',
            field=models.CharField(default='#d71920', max_length=20),
        ),
        migrations.AddField(
            model_name='shortsvideo',
            name='frame_secondary_color',
            field=models.CharField(default='#2b0508', max_length=20),
        ),
        migrations.AddField(
            model_name='shortsvideo',
            name='frame_text_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='shortsvideo',
            name='rendered_video',
            field=models.FileField(blank=True, null=True, upload_to='shorts/rendered/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='shortsvideo',
            name='show_branding_strip',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shortsvideo',
            name='show_duration_badge',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shortsvideo',
            name='video_fit',
            field=models.CharField(choices=[('contain', 'Contain'), ('cover', 'Cover')], default='contain', max_length=12),
        ),
    ]
