# Generated by Django 5.2.15 on 2026-07-26 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0046_shortsvideo_channel_logo_shortsvideo_channel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetvsetting',
            name='splash_screen_seconds',
            field=models.PositiveSmallIntegerField(default=3, help_text='Mobile app splash screen duration in seconds (0-10).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
