# Generated by Django 5.2.15 on 2026-07-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0048_livetvsetting_channel_logo_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialrenderedvideo',
            name='render_origin',
            field=models.CharField(choices=[('live_broadcast', 'Live broadcast'), ('manual_mobile', 'Manual mobile render')], db_index=True, default='live_broadcast', max_length=24),
        ),
    ]
