# Generated by Django 5.2.15 on 2026-07-28 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0049_socialrenderedvideo_render_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetvsetting',
            name='ticker_height_percent',
            field=models.PositiveSmallIntegerField(default=100, help_text='Complete ticker height scale in percent (60-160).', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(160)]),
        ),
        migrations.AddField(
            model_name='livetvsetting',
            name='ticker_label_height_percent',
            field=models.PositiveSmallIntegerField(default=100, help_text='Ticker label height relative to full ticker height (50-100).', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='livetvsetting',
            name='ticker_label_width_percent',
            field=models.PositiveSmallIntegerField(default=18, help_text='Ticker label width as percentage of video width (10-40).', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(40)]),
        ),
    ]
