# Generated by Django 5.2.15 on 2026-07-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0050_livetvsetting_ticker_height_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetvchannel',
            name='pending_delete',
            field=models.BooleanField(db_index=True, default=False, editable=False, help_text='Delete requested while background processing was still active.'),
        ),
    ]
