# Generated by Django 5.2.15 on 2026-06-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_seed_default_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_hi',
            field=models.TextField(blank=True, verbose_name='Hindi description'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_hi',
            field=models.CharField(blank=True, max_length=180, verbose_name='Hindi name'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_hi',
            field=models.TextField(blank=True, verbose_name='Hindi short description'),
        ),
    ]
