from django.urls import path

from . import views

app_name = "live_tv"

urlpatterns = [
    path("api/app/push/register/", views.register_push_device_api, name="api_push_register"),
    path("api/app/home/", views.app_home_api, name="api_app_home"),
    path("api/live/current/", views.current_live_api, name="api_live_current"),
    path("api/live/channels/<slug:slug>/current/", views.current_live_api, name="api_live_channel_current"),
    path("api/live-tv/current/", views.current_live_tv_api, name="api_current"),
    path("api/live-tv/rendered-videos/", views.rendered_videos_list_api, name="api_rendered_videos"),
    path("api/live-tv/rendered-videos/<int:pk>/", views.rendered_video_detail_api, name="api_rendered_video_detail"),
    path("api/live-tv/rendered-videos/<int:pk>/download/", views.rendered_video_download_api, name="api_rendered_video_download"),
    path("api/live-tv/shorts/", views.shorts_list_api, name="api_shorts_list"),
    path("api/live-tv/shorts/<int:pk>/like/", views.shorts_like_api, name="api_shorts_like"),
    path("api/live-tv/shorts/<int:pk>/follow/", views.shorts_follow_api, name="api_shorts_follow"),
    path("api/live-tv/shorts/<int:pk>/view/", views.shorts_view_api, name="api_shorts_view"),
    path("api/live-tv/shorts/<int:pk>/share/", views.shorts_share_api, name="api_shorts_share"),
    path("api/live-tv/shorts/<int:pk>/comment/", views.shorts_comment_api, name="api_shorts_comment"),
    path("api/live-tv/meta/", views.mobile_live_tv_meta_api, name="api_meta"),
    path("api/live-tv/admin/login/", views.mobile_admin_login_api, name="api_admin_login"),
    path("api/live-tv/admin/logout/", views.mobile_admin_logout_api, name="api_admin_logout"),
    path("api/live-tv/admin/dashboard/", views.mobile_admin_dashboard_api, name="api_admin_dashboard"),
    path("api/live-tv/admin/channels/save/", views.mobile_admin_channel_save_api, name="api_admin_channel_save"),
    path("api/live-tv/admin/settings/save/", views.mobile_admin_settings_save_api, name="api_admin_settings_save"),
    path("api/live-tv/admin/facebook-live/save/", views.mobile_admin_facebook_live_save_api, name="api_admin_facebook_live_save"),
    path("api/live-tv/admin/facebook-live/start/", views.mobile_admin_facebook_live_start_api, name="api_admin_facebook_live_start"),
    path("api/live-tv/admin/facebook-live/stop/", views.mobile_admin_facebook_live_stop_api, name="api_admin_facebook_live_stop"),
    path("api/live-tv/admin/facebook-live/status/", views.mobile_admin_facebook_live_status_api, name="api_admin_facebook_live_status"),
    path("api/live-tv/admin/channels/<int:pk>/delete/", views.mobile_admin_channel_delete_api, name="api_admin_channel_delete"),
    path("api/live-tv/admin/shorts/upload/", views.mobile_admin_shorts_upload_api, name="api_admin_shorts_upload"),
    path("api/live-tv/admin/render-social-video/", views.mobile_admin_render_social_video_api, name="api_admin_render_social_video"),
    path("api/live-tv/admin/render-social-video/<int:pk>/status/", views.mobile_admin_render_social_video_status_api, name="api_admin_render_social_video_status"),
    path("api/live-tv/admin/rendered-videos/<int:pk>/update/", views.mobile_admin_rendered_video_update_api, name="api_admin_rendered_video_update"),
    path("api/live-tv/admin/rendered-videos/<int:pk>/delete/", views.mobile_admin_rendered_video_delete_api, name="api_admin_rendered_video_delete"),
    path("api/live-tv/admin/media-downloads/start/", views.mobile_admin_media_download_start_api, name="api_admin_media_download_start"),
    path("api/live-tv/admin/media-downloads/<int:pk>/status/", views.mobile_admin_media_download_status_api, name="api_admin_media_download_status"),
    path("api/live-tv/admin/media-downloads/<int:pk>/update/", views.mobile_admin_media_download_update_api, name="api_admin_media_download_update"),
    path("api/live-tv/admin/media-downloads/<int:pk>/delete/", views.mobile_admin_media_download_delete_api, name="api_admin_media_download_delete"),
    path("live-tv/control-room/", views.live_control_dashboard, name="control_dashboard"),
    path("api/live-tv/admin/control-room/action/", views.live_control_dashboard_action_api, name="api_control_dashboard_action"),
    path("api/live-tv/admin/control-room/<str:section>/", views.live_control_dashboard_api, name="api_control_dashboard_section"),
    path("live-tv/dashboard/", views.dashboard, name="dashboard"),
    path("live-tv/dashboard/<int:pk>/delete/", views.delete_channel, name="delete_channel"),
    path("live-tv/", views.live_tv_home, name="home"),
    path("live-tv/<slug:slug>/", views.live_tv_detail, name="detail"),
]

