# Generated by Django 5.2.15 on 2026-06-23 13:30

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('excerpt', models.TextField(help_text='Short intro for listing pages and Google snippets.')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/')),
                ('image_alt_text', models.CharField(blank=True, max_length=180)),
                ('focus_keyword', models.CharField(blank=True, help_text='Main SEO keyword for this blog.', max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=220)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('canonical_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='blog_post_status_pub_idx'), models.Index(fields=['slug'], name='blog_post_slug_idx'), models.Index(fields=['is_featured', '-published_at'], name='blog_post_featured_idx')],
            },
        ),
    ]
