# Generated by Django 5.2.15 on 2026-07-13 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=2000)),
                ('source_domain', models.CharField(blank=True, max_length=255)),
                ('extractor_name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=2000)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('download_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('selected_format', models.CharField(blank=True, max_length=100)),
                ('selected_quality', models.CharField(blank=True, max_length=50)),
                ('audio_format', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('downloaded_bytes', models.BigIntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(blank=True, null=True)),
                ('relative_file_path', models.CharField(blank=True, max_length=1000)),
                ('original_filename', models.CharField(blank=True, max_length=500)),
                ('stored_filename', models.CharField(blank=True, max_length=500)),
                ('file_extension', models.CharField(blank=True, max_length=20)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='socdl_user_created_idx'), models.Index(fields=['status', '-created_at'], name='socdl_status_created_idx')],
            },
        ),
    ]
